rules:
  # bem-depth will enforce how many elements a BEM selector can contain
  bem-depth:
    - 0
    - max-depth: 1

  # border-zero will enforce whether one should use 0 or none when specifying a zero border value
  border-zero: 0

  # brace-style will enforce the use of the chosen brace style
  brace-style: 0

  # class-name-format will enforce a convention for class names
  class-name-format: 0

  # clean-import-paths will enforce whether or not @import paths should have leading underscores and/or filename extensions
  clean-import-paths: 0

  # empty-args will enforce whether or not parenthesis should be included if no arguments are defined or used, when declaring or invoking a mixin
  empty-args: 0

  # empty-line-between-blocks will enforce whether or not nested blocks should include a space between the last non-comment declaration or not
  empty-line-between-blocks:
      - 2
      - include: true

  # extends-before-declarations will enforce that extends should be written before declarations in a ruleset
  extends-before-declarations: 2

  # extends-before-mixins will enforce that extends should be written before mixins in a ruleset
  extends-before-mixins: 2

  # final-newline will enforce whether or not files should end with a newline
  final-newline: 2

  # force-attribute-nesting will enforce the nesting of attributes
  force-attribute-nesting: 0

  # force-element-nesting will enforce the nesting of elements
  force-element-nesting: 0

  # force-pseudo-nesting will enforce the nesting of pseudo elements/classes
  force-pseudo-nesting: 0

  # function-name-format will enforce a convention for function names
  function-name-format: 0

  # hex-length will enforce the length of hexadecimal values
  hex-length: 0

  # hex-notation will enforce the case of hexadecimal values
  hex-notation: 0

  # id-name-format will enforce a convention for ids
  id-name-format: 0

  # indentation will enforce an indentation size (in spaces) and ensure that tabs and spaces are not mixed
  indentation:
    - 0
    - size: 4
    - allow-non-nested-indentation: true

  # Don't include leading zeros on numbers
  leading-zero: 0

  # mixin-name-format will enforce a convention for mixin names
  mixin-name-format: 0

  # mixins-before-declarations will enforce that mixins should be written before declarations in a ruleset
  mixins-before-declarations: 0

  # nesting-depth will enforce how deeply a selector can be nested
  nesting-depth: 0

  # Color 'grey' should be written in its hexadecimal form #808080
  no-color-keywords: 0

  # Color literals such as 'fff' should only be used in variable declarations
  no-color-literals: 0

  no-css-comments: 0

  no-debug: 2

  # Duplicate properties are not allowed within a block
  no-duplicate-properties: 1

  # Qualifying elements are not allowed for attribute selectors
  no-empty-rulesets: 2

  no-extends: 0

  no-ids: 0

  no-important: 0

  no-invalid-hex: 0

  # no-mergeable-selectors will enforce that selectors aren't repeated and that their properties are merged
  no-mergeable-selectors: 2

  no-misspelled-properties: 1

  no-qualifying-elements: 0

  # No trailing whitespace allowed
  no-trailing-whitespace: 0

  # Don't include trailing zeros on numbers
  no-trailing-zero: 0

  # The keyword `all` should not be used with the property `transition`
  no-transition-all: 0

  # no-url-protocols will enforce that protocols and domains are not used within urls
  no-url-protocols: 0

  # Vendor prefixes should not be used
  no-vendor-prefixes: 1

  # @warn not allowed
  no-warn: 0

  # Only one declaration allowed per line
  one-declaration-per-line: 0

  # @extend must be used with a %placeholder
  placeholder-in-extend: 0

  placeholder-name-format: 0

  property-sort-order: 0

  property-units: 0

  quotes: 0

  shorthand-values: 0

  single-line-per-selector: 0

  space-after-bang: 0

  space-after-comma: 0

  space-after-colon: 0

  space-around-operator: 0

  space-before-bang: 0

  space-before-brace: 2

  space-before-colon: 0

  space-between-parens: 0

  trailing-semicolon: 0

  # Quotes around URLs are required
  url-quotes: 1

  variable-name-format: 0

  zero-unit: 2
